### ISSUE TITLE
Project Update?

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [zignig/astralboot#7]
I would like to either collaborate with you on this or learn of things planned already that you have yet to get working on so that I could contribute in some way, shape or form...

Also Happy New Years!

**Comment by zignig** [comment]
This project has been unmaintained for quite some time. It uses gb , rather than the newer mod system that go uses .

I don't think it  would need much of a rewrite in the code to get it working.

If you would like to develop it, I would be more than happy to answer any questions that you have.

**Comment by OpenOS-Project-Creator-Founder** [comment]
> This project has been unmaintained for quite some time. It uses gb , rather than the newer mod system that go uses .
> 
> I don't think it  would need much of a rewrite in the code to get it working.
> 
> If you would like to develop it, I would be more than happy to answer any questions that you have. 
> 


Would you like to discuss a possible collaborative partnership to upstream & maintain it with me & others from the OpenOS-Project & One-Open-Collective which is the collaborative-arm of OpenOS-Project that holds other developers & projects.
